### ISSUE TITLE
Only sets wallpaper of active desktop on macOS

### ISSUE THREAD

**Issue by fenhl** [reujab/wallpaper.rs#3]
On macOS, the `set_from_path` function only sets the wallpaper of the desktop that's currently in the foreground. If a fullscreen app is active, nothing happens.

**Comment by fenhl** [comment]
I tested with version 3.2.0 and this is still not fixed. The behavior is the same as before.

**Comment by fenhl** [comment]
To be clear, when I say desktop I mean virtual desktop (the ones sitting next to fullscreen apps in Mission Control), not physical monitors.

**Comment by FormalSnake** [comment]
I also have this issue in the fork
