### ISSUE TITLE
XFCE error changing wallpaper

### ISSUE THREAD

**Issue by davidpob99** [reujab/wallpaper.rs#4]
When I try to change the wallpaper in XFCE (Arch Linux) I get this error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "xfconf-query exited with status code 1"', src/libcore/result.rs:1084:5`

This is because this library uses this command to change the wallpaper in XFCE: `xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s PATH`, but in Arch (I do not know other OS) the property is `/backdrop/screen0/monitorLVDS1/workspace0/last-image` instead of `/backdrop/screen0/monitor0/workspace0/last-image`

**Comment by gorun-efedus** [comment]
i have exactly same problem when calling wallpaper::set_from_url inside a XUbuntu 20.04.1 LTS virtualbox guest machine. It is XFCE 4.14

I have one screen and 3 workspaces, but for me it is another location : 
_$ xfconf-query -c xfce4-desktop -l
/backdrop/screen0/monitor0/image-path
/backdrop/screen0/monitor0/image-show
/backdrop/screen0/monitor0/image-style
/backdrop/screen0/monitor1/image-path
/backdrop/screen0/monitor1/image-show
/backdrop/screen0/monitor1/image-style
/backdrop/screen0/monitor2/image-path
/backdrop/screen0/monitor2/image-show
/backdrop/screen0/monitor2/image-style
/backdrop/screen0/monitor3/image-path
/backdrop/screen0/monitor3/image-show
/backdrop/screen0/monitor3/image-style
/backdrop/screen0/monitorVirtual1/workspace0/backdrop-cycle-enable
/backdrop/screen0/monitorVirtual1/workspace0/backdrop-cycle-random-order
/backdrop/screen0/monitorVirtual1/workspace0/backdrop-cycle-timer
/backdrop/screen0/monitorVirtual1/workspace0/color-style
/backdrop/screen0/monitorVirtual1/workspace0/image-style
/backdrop/screen0/monitorVirtual1/workspace0/last-image
/backdrop/screen0/monitorVirtual1/workspace1/color-style
/backdrop/screen0/monitorVirtual1/workspace1/image-style
/backdrop/screen0/monitorVirtual1/workspace1/last-image
/backdrop/screen0/monitorVirtual1/workspace2/color-style
/backdrop/screen0/monitorVirtual1/workspace2/image-style
/backdrop/screen0/monitorVirtual1/workspace2/last-image
/backdrop/screen0/monitorVirtual1/workspace3/color-style
/backdrop/screen0/monitorVirtual1/workspace3/image-style
/backdrop/screen0/monitorVirtual1/workspace3/last-image
/desktop-icons/file-icons/show-filesystem
/desktop-icons/file-icons/show-home
/desktop-icons/file-icons/show-removable
/desktop-icons/file-icons/show-trash
/desktop-icons/gravity
/desktop-icons/icon-size
/desktop-icons/primary
/desktop-icons/style
/desktop-icons/tooltip-size
/last/window-height
/last/window-width
/windowlist-menu/show-add-remove-workspaces
/windowlist-menu/show-submenus_

**Comment by fblais** [comment]
Also have a problem in XFCE, mine is Linux Mint 20.1, based on Ubuntu 20.04LTS.
Please fix!

Thanks.
